name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu

            if [ ! -d "NoteVault" ]; then
              git clone https://${{ secrets.GH_PAT }}@github.com/INISHKASHYAP/NoteVault.git
            fi

            cd NoteVault
            git pull origin main

            npm install
            npm run build

            sudo cp -r build/* /var/www/html/
