name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu

            # Clone if not already cloned
            if [ ! -d "NoteVault" ]; then
              git clone https://${{ secrets.GH_PAT }}@github.com/INISHKASHYAP/NoteVault.git
            fi

            cd NoteVault
            git pull origin main

            # Install dependencies
            npm install

            # Install PM2 if not installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Stop previous instance
            pm2 delete notevault || true

            # Start the app with PM2
            pm2 start index.js --name notevault
